// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clusters.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const markStaleClustersAsDeleted = `-- name: MarkStaleClustersAsDeleted :execresult
UPDATE clusters
SET is_deleted = TRUE,
    deleted_at = CURRENT_TIMESTAMP
WHERE project_id = ?
    AND updated_at < ?
    AND is_deleted = FALSE
`

type MarkStaleClustersAsDeletedParams struct {
	ProjectID string
	SyncedAt  time.Time
}

// MarkStaleClustersAsDeleted marks clusters as deleted if they have not been updated since the given timestamp.
func (q *Queries) MarkStaleClustersAsDeleted(ctx context.Context, arg MarkStaleClustersAsDeletedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markStaleClustersAsDeleted, arg.ProjectID, arg.SyncedAt)
}

const upsertCluster = `-- name: UpsertCluster :exec
INSERT INTO clusters (
        id,
        project_id,
        name,
        cluster_type,
        cloud_provider,
        region,
        create_timestamp,
        tidb_version,
        cluster_status
    )
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY
UPDATE
    project_id = VALUES(project_id),
    name = VALUES(name),
    cluster_type = VALUES(cluster_type),
    cloud_provider = VALUES(cloud_provider),
    region = VALUES(region),
    create_timestamp = VALUES(create_timestamp),
    tidb_version = VALUES(tidb_version),
    cluster_status = VALUES(cluster_status)
`

type UpsertClusterParams struct {
	ID              string
	ProjectID       string
	Name            string
	ClusterType     string
	CloudProvider   string
	Region          string
	CreateTimestamp int64
	TidbVersion     string
	ClusterStatus   string
}

func (q *Queries) UpsertCluster(ctx context.Context, arg UpsertClusterParams) error {
	_, err := q.db.ExecContext(ctx, upsertCluster,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.ClusterType,
		arg.CloudProvider,
		arg.Region,
		arg.CreateTimestamp,
		arg.TidbVersion,
		arg.ClusterStatus,
	)
	return err
}
