// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Project struct {
	ID              string
	OrgID           string
	Name            string
	ClusterCount    sql.NullInt32
	UserCount       sql.NullInt32
	CreateTimestamp sql.NullInt64
	AwsCmekEnabled  sql.NullBool
	FetchedAt       sql.NullTime
}
