// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Cluster struct {
	ID              string
	ProjectID       string
	Name            string
	ClusterType     string
	CloudProvider   string
	Region          string
	CreateTimestamp int64
	TidbVersion     sql.NullString
	ClusterStatus   sql.NullString
	IsDeleted       bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}

type ClusterNode struct {
	ClusterID        string
	NodeName         string
	ComponentType    string
	AvailabilityZone string
	NodeSize         string
	StorageSizeGib   sql.NullInt32
	Status           string
	IsDeleted        bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        sql.NullTime
}

type Project struct {
	ID              string
	OrgID           string
	Name            string
	ClusterCount    int32
	UserCount       int32
	CreateTimestamp int64
	AwsCmekEnabled  bool
	FetchedAt       time.Time
}
