// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const upsertProject = `-- name: UpsertProject :exec
INSERT INTO
    projects (
        id,
        org_id,
        name,
        cluster_count,
        user_count,
        create_timestamp,
        aws_cmek_enabled
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    org_id = VALUES(org_id),
    name = VALUES(name),
    cluster_count = VALUES(cluster_count),
    user_count = VALUES(user_count),
    create_timestamp = VALUES(create_timestamp),
    aws_cmek_enabled = VALUES(aws_cmek_enabled)
`

type UpsertProjectParams struct {
	ID              string
	OrgID           string
	Name            string
	ClusterCount    sql.NullInt32
	UserCount       sql.NullInt32
	CreateTimestamp sql.NullInt64
	AwsCmekEnabled  sql.NullBool
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) error {
	_, err := q.db.ExecContext(ctx, upsertProject,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.ClusterCount,
		arg.UserCount,
		arg.CreateTimestamp,
		arg.AwsCmekEnabled,
	)
	return err
}
