// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package db

import (
	"context"
)

const listProjectIDsWithClusters = `-- name: ListProjectIDsWithClusters :many
SELECT
    id
FROM
    projects
WHERE
    cluster_count > 0
    AND DATE(fetched_at) = (
        SELECT
            DATE(MAX(fetched_at))
        FROM
            projects
    )
`

func (q *Queries) ListProjectIDsWithClusters(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProjectIDsWithClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :exec
INSERT INTO
    projects (
        id,
        org_id,
        name,
        cluster_count,
        user_count,
        create_timestamp,
        aws_cmek_enabled
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    org_id = VALUES(org_id),
    name = VALUES(name),
    cluster_count = VALUES(cluster_count),
    user_count = VALUES(user_count),
    create_timestamp = VALUES(create_timestamp),
    aws_cmek_enabled = VALUES(aws_cmek_enabled)
`

type UpsertProjectParams struct {
	ID              string
	OrgID           string
	Name            string
	ClusterCount    int32
	UserCount       int32
	CreateTimestamp int64
	AwsCmekEnabled  bool
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) error {
	_, err := q.db.ExecContext(ctx, upsertProject,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.ClusterCount,
		arg.UserCount,
		arg.CreateTimestamp,
		arg.AwsCmekEnabled,
	)
	return err
}
