--
name: Test msk CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: '1.24.4'

      - name: Install dependencies
        run: go mod download

      - name: Run msk clusterinfo
        run: go run main.go clusterinfo
      - name: Run msk generate-notice
        run: go run main.go generate-notice
      - name: Run msk notify
        run: go run main.go notify
